name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: docker run raz0red/devkitppc /opt/devkitpro/pacman/bin/pacman -Q 
    - run: docker run -v $(pwd):/source raz0red/devkitppc /source/dist.sh